server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distancelearning-course
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
